#--Resolve Runtime Dependency--------------------------------------------------------------------------------------
FROM mcr.microsoft.com/dotnet/core/runtime:3.1-buster-slim AS base
WORKDIR /app

#--Resolve SDK/Compilation Dependency--
FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build

# Copy source directory into ELO folder.
COPY ["src/", "ELO/"]

# Restore csproj dependencies
RUN dotnet restore "ELO/ELO.csproj"
RUN dotnet build "ELO/ELO.csproj" -c Release -o /app/build

#--Publish App-----------------------------------------------------------------------------------------------------
FROM build AS publish
RUN dotnet publish "ELO/ELO.csproj" -c Release -o /app/publish

#--Run Compiled App on Runtime-------------------------------------------------------------------------------------
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "ELO.dll"]